siteTitle: lenin's blog
dateFormat: MMM D, YYYY
perPage: 5
postDir: posts
templateDir: templates

# add menu items
menu:
  - name: blog
    link: /
  - name: root
    link: https://leninhasda.me

# these are the config you don't want to change too often
postRoute: post
tagRoute: tags
searchRoute: search
